version: "3.4"
services:
  apps:
    build: .
    working_dir: "/home/ubuntu/jekyll"
    ports:
      - 4000:4000
    volumes:
      # 설정 파일들
      - ./:/home/ubuntu/jekyll
    # command: /bin/sh
    command: /bin/sh -c "bundle install && /bin/sh"
    stdin_open: true # docker run -i
    tty: true # docker run -t
